# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    ports:
      - "5432:5432"
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: tentool
      POSTGRES_DB: tentool

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080